### ISSUE TITLE
security-vocab contexts returning 404

### ISSUE THREAD

**Issue by lukehowkins** [w3c-ccg/w3c-ccg.github.io#23]
Both of these are returning 404s:
https://w3c-ccg.github.io/security-vocab/contexts/security-v2.jsonld
https://w3c-ccg.github.io/security-vocab/contexts/security-v1.jsonld

**Comment by nightpool** [comment]
This issue was raised in the SocialCG irc room today, as many projects depend on the context definition being available for parsing JSON-LD signatures
