### ISSUE TITLE
Repo for Data Minimization and Selective Disclosure?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/w3c-ccg.github.io#3]

**Comment by msporny** [comment]
I'm wondering if this is a sub-section of the Verifiable Claims Data Model spec... under Privacy Considerations?

**Comment by kimdhamilton** [comment]
Actually, my original issue was written assuming we're merging the [DVCG organization](https://github.com/w3c-dvcg) and this one, which we are not. Instead I imagine any signature-related specs would go there, but it makes sense that we'd also want a higher level discussion in VC data model spec

**Comment by kimdhamilton** [comment]
This is done
