### ISSUE TITLE
Repo for Verifiable Claims Lifecycle?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/w3c-ccg.github.io#4]

**Comment by msporny** [comment]
+1, although David Chadwick and I were talking and it may be better to keep that spec in a Google Doc until it's more fully formed. Going to Respec is typically a one-way trip, and once it's in Respec, it's much harder to make modifications.

**Comment by kimdhamilton** [comment]
Good point. Instead, I could link to the google docs on our site for now

**Comment by kimdhamilton** [comment]
Added links to VC draft docs on index.html. We'll revisit as we get closer to respec readiness
