### ISSUE TITLE
Repo for VC Browser Polyfill?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/w3c-ccg.github.io#5]

**Comment by msporny** [comment]
Spec-Ops is currently hosting that repo: https://github.com/Spec-Ops/credentials-polyfill ... and I know @dlongley is currently generalizing that framework to work for both Web Payments and Verifiable Claims here: https://github.com/digitalbazaar/web-request-mediator/tree/implementation ... so let's hold off on a repo until that work settles (which should happen by the end of September/October at the latest).

**Comment by kimdhamilton** [comment]
Sounds good; we'll wait

**Comment by kimdhamilton** [comment]
This issue was moved to w3c-ccg/community#11
